import type { Metadata } from 'next';
import './globals.css';
import { IChildrenProps } from '@/interfaces';
import UiLibraryProvider from '@/providers/UiLibraryProvider';
import { ClerkProvider } from '@clerk/nextjs';

export const metadata: Metadata = {
  title: 'Events Booking',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: IChildrenProps) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body>
          <UiLibraryProvider>{children}</UiLibraryProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
