import type { Metadata } from 'next';
import './globals.css';
import 'remixicon/fonts/remixicon.css';
import { IChildrenProps } from '@/interfaces';
import UiLibraryProvider from '@/providers/UiLibraryProvider';
import { ClerkProvider } from '@clerk/nextjs';
import LayoutProvider from '@/providers/LayoutProvider';

export const metadata: Metadata = {
  title: 'Events Booking',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: IChildrenProps) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className="bg-gray-200 h-screen">
          <UiLibraryProvider>
            <LayoutProvider>{children}</LayoutProvider>
          </UiLibraryProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
