import type { Metadata } from 'next';
import './globals.css';
import { IChildrenProps } from '@/interfaces';
import UiLibraryProvider from '@/providers/UiLibraryProvider';

export const metadata: Metadata = {
  title: 'Events Booking',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: IChildrenProps) {
  return (
    <html lang="en">
      <body>
        <UiLibraryProvider>{children}</UiLibraryProvider>
      </body>
    </html>
  );
}
